FROM node:8

RUN apt-get update && apt-get install -y zip

RUN npm install remme

RUN mkdir /lambdas

RUN mkdir /lambdas/transferTokensLambda && cp -r /node_modules/ /lambdas/transferTokensLambda

ADD src/lambdas/transferTokensLambdaHandler.js /lambdas/transferTokensLambda/

RUN cd /lambdas/transferTokensLambda && zip -9r transferTokensLambda.zip .

CMD sleep 7200
